### PR TITLE
Added Rentable Theaters utilizing PointShop Points

### PR DESCRIPTION
**Pull request by WinterPhoenix96**
- Can be enabled/disabled by running cinema_rentables 1; is disabled by default
- Point Cost per Minute of Rent can be adjusted by setting cinema_rentables_cost
- Has support for both PointShop and PointShop 2, either of which must be installed to use

### CODE REVIEW

**Comment by samuelmaddock** [comment]
I think I would rather see this pull request built as an addon rather than a new feature to the gamemode. I have no plans to maintain the code of this feature; it also adds overhead even when not in use (networking additional variables).

I'm assuming the main reason you submitted this as a pull request is that it's not possible to implement without modifying the gamemode itself. If you want to instead submit a PR with additional hooks/functions added where needed, I'd consider merging that.

**Comment by WinterPhoenix96** [comment]
Which would you prefer? A module under gamemode/modules/ containing the code needed to run it or something outside of the cinema directory period, implemented like an addon?

**Comment by samuelmaddock** [comment]
I'd prefer an addon in which the code is completely separate. The idea being to add hooks/functions to Cinema necessary to allow an extension without modifying the core gamemode.

**Comment by WinterPhoenix96** [comment]
Okay, so say a folder in the top level of this Repo? On the same level as the cinema directory?

**Comment by samuelmaddock** [comment]
Sorry, I don't think I'm being clear enough. I'd rather not have the feature a part of the gamemode. I believe it would be better suited as an independent addon if possible.

**Comment by WinterPhoenix96** [comment]
Ah I see. Alright. I'll stick a link in here or something once I'm done.

**Pull request closed without merging**
