### PR TITLE
fixed privileged theater flag and Flags not being accessed bitwise

### PR DESCRIPTION
**Pull request by neico**
Just wrote this down out of my head, since I don't have a test server running currently it would be good if someone could check if this change doesn't break existing maps and behavior.

### CODE REVIEW

**Comment by zachcheatham** [comment]
Had to change that flag on a server to stop IsPrivate() returning true on VIP theaters. Glad someone already made a pr for it.

**Comment by neico** [comment]
"Already", it's been over a year by now...

**Comment by zachcheatham** [comment]
Wow, didn't even realize that said 2014. Why hasn't this been merged?

**Comment by samuelmaddock** [comment]
Today is the day

**Comment by samuelmaddock** [comment]
I added 6168a2ab6878f86179d48f4e30b72b6a958bd3d7 to attempt to fix maps using the old privileged flag value.

**Pull request merged**
