### PR TITLE
Fix for Twitch and YouTube

### PR DESCRIPTION
**Pull request by CattoGamer**
Lets be honest, Twitch has changed the API so many times that it's just annoying. With this change it becomes completely independent of Twitch's APIs and the old method with theater.js. That so many people only want to watch his favorite streamers stream and no videos.

So in this variant only livestream is supported, period.
@samuelmaddock I'm sorry to mention you, but I'd like ask you to migrate this PR and take please 15 minutes of you freetime to make a small instruction that Twitch requires to have CEFCodecFix (https://github.com/solsticegamestudios/GModCEFCodecFix)

Nevertheless I want to apologize for not making a single lua file instead of creating it in 3 scripts in a subdirectory, this is my habit and intended to make the isolation of CLIENT and SERVER environment.

#Edit 1

This PR now also contains the fix for YouTube, the code was taken from the media player (https://github.com/samuelmaddock/gm-mediaplayer/blob/master/lua/mediaplayer/services/youtube/init.lua)

### CODE REVIEW

**Comment by Bluscream** [comment]
Brony lmao.

**Comment by pudimdecana** [comment]
Hi. 
I got Faruk's last updates and all.
But whenever I try to request a Twitch livestream, it wont let me, and console shows this:
image

**Comment by FarukGamer** [comment]
Are you on the x86-64 branch and installed he CEF Codec fix?
https://github.com/solsticegamestudios/GModCEFCodecFix

**Comment by CattoGamer** [comment]
@pudimdecana works for me 🤔 
grafik

Make sure you are on the x86-64 branch and applied the Codec Fix patch
https://github.com/solsticegamestudios/GModCEFCodecFix/releases

grafik

**Comment by pudimdecana** [comment]
Yeah, I always used chromium branch because of youtube videos and stuff.
Codec was already installed. I will try reinstalling the addon.
image

**Review by Mauvemau — CHANGES_REQUESTED** [review]
I rearranged the script into a single sh_twitch.lua file to fit the original style of the code. 

The sh_load.lua script also grabs it up and includes it automatically, as long as the file is named with "cl_" for client, "sh_" for shared, "sv_" for server, at the beginning.

It might need a few more arrangements for it to be completely neat.
There are no significant changes to the code, i just thought this was important to note.

```
local SERVICE = {}

SERVICE.Name = "Twitch.TV Stream"
SERVICE.IsTimed = false
SERVICE.TheaterType = THEATER_PRIVATE

local Ignored = {
	["video"] = true,
	["directory"] = true,
	["downloads"] = true,
}

function SERVICE:Match( url )
	return url.host and url.host:match("twitch.tv")
end

function SERVICE:GetURLInfo( url )

	if url.path then
		print("Checking Twitch")
		local data = url.path:match("/([%w_]+)")
		if (data and not Ignored[data]) then return { Data = data } end
	end

	print("Url not catched")
	return false
	
end

local THUMB_URL = "https://static-cdn.jtvnw.net/previews-ttv/live_user_%s-1280x720.jpg"

function SERVICE:GetVideoInfo( data, onSuccess, onFailure )
	local info = {}
	info.title = ("Twitch Stream: %s"):format(data)
	info.thumbnail = THUMB_URL:format(data)

	if onSuccess then
		pcall(onSuccess, info)
	end
	
	if onFailure then
		print("Failed to load stream.")
	end
end

-- CL

if CLIENT then

	local TWITCH_URL = "https://player.twitch.tv/?channel=%s&parent=pixeltailgames.com"
	local THEATER_JS = [[
		function testSelector(elem, dataStr) {
			var data = document.querySelectorAll( elem + "[data-test-selector]")
			for (let i=0; i<data.length; i++) {
				var selector = data[i].dataset.testSelector
				if (!!selector && selector === dataStr) {
					return data[i]
					break
				}
			}
		}
		function target(dataStr) {
			var data = document.querySelectorAll( "button[data-a-target]")
			for (let i=0; i<data.length; i++) {
				var selector = data[i].dataset.aTarget
				if (!!selector && selector === dataStr) {
					return data[i]
					break
				}
			}
		}
		function build(player) {
			window.player = player;
			if (!window.theater) {
				class CinemaPlayer {
					get player() {
						return window.player;
					}
					setVolume(volume) {
						if (!!this.player) {
							this.player.volume = volume / 100;
						}
					}
					enableHD(on) { }
				};
				window.theater = new CinemaPlayer();
			}
		}
		function check() {
			var mature = target("player-overlay-mature-accept")
			if (!!mature) {mature.click(); return;}
			var player = document.getElementsByTagName('video')[0];
			if (!testSelector("div", "sad-overlay") && !!player && player.paused == false && player.readyState == 4) {
				build(player);
				clearInterval(intervalId);
			}
		}
		var intervalId = setInterval(check, 150);
	]]

	function SERVICE:LoadVideo( Video, panel )
		panel:Stop()
		panel:OpenURL( TWITCH_URL:format( Video:Data() ) )

		panel.OnFinishLoading = function(pnl)
			pnl:RunJavascript(THEATER_JS)
		end
	end

end
theater.RegisterService( "twitchstream", SERVICE )
```

I apologize for leaving this chunk of text here, i have little experience on this website.

**Comment by pudimdecana** [comment]
So with this file change.. We have to delete the twitchstream folder and go back to having only the sh_twitch.lua file?
But it would have to change the other hooks made in another file, right?

**Comment by CattoGamer** [comment]
What's the purpose of making it into a single file?

For example, Imagine your have APIs Keys in the code, do you want that it get exposed to the client? What would happend when it get abused?

**Comment by WinterPhoenix** [comment]
Just a warning you guys, Sam doesn't have access to do anything with this repository anymore, and the rest of pixelTail hasn't been interested in working with Cinema in years.

Keep the suggestions coming, because I'm planning on folding a lot of them into a fork I'm working on, [https://github.com/solsticegamestudios/cinema](https://github.com/solsticegamestudios/cinema) , but they'll likely fall on deaf ears here.

**Comment by Bluscream** [comment]
Watched and starred

**Comment by FreddyXBR** [comment]
So, how to fix it? I'm having a very difficulty.
(ye my english is bad, sorry)

**Comment by Mauvemau** [comment]
> What's the purpose of making it into a single file?
> 
> For example, Imagine your have APIs Keys in the code, do you want that it get exposed to the client? What would happend when it get abused?

You are correct. For a youtube API key, i don't see it as a big worryabout. But in case of database credentials, or other things, you want that nowhere near the client.

The only reason i would use a shared script is to avoid repeating code on both server and client. But in this case it's just to fit the original script.

Anyway, thanks for the fix!

**Comment by pudimdecana** [comment]
Just want yall to know that I figured it out
The Non-Timed requests only work on PRIVATE ROOMS
Therefore, it worked fine for me. 
Sorry for the inconvenience and thanks for the help.

**Comment by Blueberryy** [comment]
Good fix i hope madoc will merge it

**Comment by CattoGamer** [comment]
Instead of waiting for PixelTailGames to fix it, I took the effort to fix it in my fork. 
https://github.com/FarukGamer/cinema

YouTube and Twitch now runs smoothly on this fork, keep in mind on Twitch you can only watch live streams.
For YouTube only you need Chromium (or x86-64) Beta, otherwise for Twitch you need CEF Codec Fix.

Furthermore I have implemented a search and page function from my closed source version of Cinema.
If someone takes the code for the search function, so please give credits. 

unknown

**Comment by Blueberryy** [comment]
> Instead of waiting for PixelTailGames to fix it, I took the effort to fix it in my fork.
> https://github.com/FarukGamer/cinema
> 
> YouTube and Twitch now runs smoothly on this fork, keep in mind on Twitch you can only watch live streams.
> For YouTube only you need Chromium (or x86-64) Beta, otherwise for Twitch you need CEF Codec Fix.
> 
> Furthermore I have implemented a search and page function from my closed source version of Cinema.
> If someone takes the code for the search function, so please give credits.
> 
> unknown

Great thanks

**Pull request closed without merging**
